### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by kmui2** [RiseCareerAcademy/Rise#1]
As a user, the first screen to display is the welcome screen.

## Checklist
- [x] Logo placed
- [x] Buttons placed
- [x] Text done
- [ ] Layout done

## Getting Started
1. Follow [setup procedure](https://github.com/GeekyAnts/NativeBase#4-getting-started) for installing NativeBase
2. Add some [buttons](https://docs.nativebase.io/Components.html#button-def-headref) to the screen
3. Add the Rise logo to the screen using the [Image API](https://facebook.github.io/react-native/docs/image)

![welcome](https://user-images.githubusercontent.com/17896701/46122118-9c0f1480-c1dc-11e8-8654-eaf187fd0f3f.png)

**Comment by meenereem** [comment]
@rroloff need image of Rise logo

**Comment by rroloff** [comment]
layout for itr 2
