### ISSUE TITLE
integrate database for bio

### ISSUE THREAD

**Issue by rroloff** [RiseCareerAcademy/Rise#140]

**Comment by rroloff** [comment]
Need help correctly changing the bio state. Currently I can put info to bio but this info is null. I also need help getting the global email and password field so i can automatically get user id
https://github.com/RiseCareerAcademy/Rise/blob/rita-test/screens/Profile1/Profile.js
My changes start at 181
@kmui2

**Comment by kmui2** [comment]
Use `this.state.aboutMe` rather than `this.aboutMe`.
