### ISSUE TITLE
Student Sign Up Screen

### ISSUE THREAD

**Issue by kmui2** [RiseCareerAcademy/Rise#2]
After completing #1:

When the user clicks on the `Student` button in the welcome screen, the user is taken to the Student Email Sign Up screen:

## Checklist
- [ ] Can navigate from welcome screen to sign up screen
- [ ] Text inputs placed
- [ ] Submit button placed
- [ ] Checkbox placed
- [ ] Labels placed
- [ ] Layout done

## Getting Started
1. Install [react-navigation](https://reactnavigation.org/docs/en/getting-started.html) using npm
2. Follow [instructions](https://reactnavigation.org/docs/en/hello-react-navigation.html) on how to use react-navigation.
3. Use native-base UI components to build the sign up screen:
    - [Regular Textbox](https://docs.nativebase.io/Components.html#regular-textbox-headref)
    - [Check Box](https://docs.nativebase.io/Components.html#checkbox-headref)
    - [Outline Button](https://docs.nativebase.io/Components.html#button-outline-headref)

![student email sign up 2](https://user-images.githubusercontent.com/17896701/46122552-e2fe0980-c1de-11e8-9a85-7f549e025085.png)

**Comment by rroloff** [comment]
itr 2
